- name: Install remi repo
  ansible.builtin.yum:
    name: https://rpms.remirepo.net/enterprise/remi-release-8.rpm
    state: latest
    disable_gpg_check: true

- name: Enable remi module
  ansible.builtin.shell: yum module enable redis:remi-6.2 -y

- name: Install redis
  ansible.builtin.yum:
    name: redis
    state: latest

- name: Modifying Listening address
  ansible.builtin.replace:
    path: /etc/redis.conf
    regexp: '127.0.0.1'
    replace: '0.0.0.0'

- name: Modifying Listening address
  ansible.builtin.replace:
    path: /etc/redis/redis.conf
    regexp: '127.0.0.1'
    replace: '0.0.0.0'

- name: Enabling and restarting redis Server
  ansible.builtin.systemd:
    state: restarted
    name: "{{ component }}"
    enabled: true