- name: Configuring maven server
  ansible.builtin.import_role:
    name: common
    tasks_from: maven.yml

- name: Configuring mysql_schema
  ansible.builtin.import_role:
    name: common
    tasks_from: mysql_schema.yml