- name: Installing mysql_schema
  ansible.builtin.yum:
    name: mysql
    state: latest

- name: Loading mysql_Schema
  ansible.builtin.shell: mysql -h mysql-dev.sadguru.shop -uroot -pRoboShop@1 </app/schema/{{ component }}.sql